// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltamzemjbrhiuvyjzaec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0YW16ZW1qYnJoaXV2eWp6YWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjIxNzYsImV4cCI6MjA3MDM5ODE3Nn0.kY9iRw23CiHZPgW0Gk1jNDXY713s1ARYTCKBu_NcRTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});